-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 11:02:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilizadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utilizadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilizadores` (
  `idUtilizadores` INT NOT NULL DEFAULT 1,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(32) NULL,
  PRIMARY KEY (`idUtilizadores`),
  UNIQUE INDEX `idUtilizadores_UNIQUE` (`idUtilizadores` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartões`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cartões` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cartões` (
  `CardID` INT NOT NULL DEFAULT 1,
  `Titulo` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Ligação` VARCHAR(45) NULL,
  `UserID` INT NOT NULL,
  `Notif` BIT(1) NULL,
  `Timer` TIMESTAMP(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CardID`),
  UNIQUE INDEX `CardID_UNIQUE` (`CardID` ASC) VISIBLE,
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Utilizadores` (`idUtilizadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
